actions:
  rustfmt:
    run: cargo fmt -- --unstable-features --check --skip-children {files}
    fix: cargo fmt -- {files}
    include: "*.rs"
  clippy:
    run: cargo clippy --all-targets --all-features
    include:
      - "*.rs"
      - "Cargo.toml"
