[package]
name = "classify-client"
version = "0.1.0"
authors = ["Michael Cooper <mcooper@mozilla.com>"]
edition = "2018"

[dependencies]
actix = "^0.7.6"
actix-web = "^0.7.14"
chrono = { version = "^0.4", features = ["serde"] }
config = { version = "^0.9.1", default_features = false }
ctrlc = "^3.1.1"
futures = "*"
lazy_static = "^1.2.0"
maxminddb = "^0.11.0"
serde = "^1.0.80"
serde_derive = "^1.0.80"
serde_json = "^1.0.33"
