# These environment variables must be set in CircleCI UI
#
# DOCKERHUB_REPO - docker hub repo, format: <username>/<repo>
# DOCKER_EMAIL   - login info for docker hub
# DOCKER_USER
# DOCKER_PASS
#
version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4


jobs:
  test-machine:
    machine:
      image: circleci/classic:latest
    steps:
    - checkout
    - run:
        name: Install rust
        command: |
          sudo apt-get update
          RUSTUP_HOME=/usr/local/rustup
          CARGO_HOME=/usr/local/cargo
          RUST_VERSION=1.35.0
          set -eux
          rustArch='x86_64-unknown-linux-gnu'
          rustupSha256='a46fe67199b7bcbbde2dcbc23ae08db6f29883e260e23899a88b9073effc9076'
          url="https://static.rust-lang.org/rustup/archive/1.18.3/${rustArch}/rustup-init"
          wget "$url"
          echo "${rustupSha256} *rustup-init" | sha256sum -c -
          chmod +x rustup-init
          ./rustup-init -y --no-modify-path --default-toolchain $RUST_VERSION
          rm rustup-init
          echo "export PATH=$HOME/.cargo/bin:$PATH" >> $BASH_ENV
          source $BASH_ENV
          rustup --version
          cargo --version
          rustc --version
    - run:
        name: Setup
        command: |
          set -eux
          sudo apt-get upgrade -y
          sudo apt-get install -y cmake g++ pkg-config jq libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev libiberty-dev
          cargo install cargo-kcov
          mkdir -p /tmp/kcov
          cd /tmp/kcov
          cargo kcov --print-install-kcov-sh | sh
          rustup component add rustfmt
          rustup component add clippy
          cargo install cargo-audit
          # Cleanup
          apt-get clean
          rm -rf /tmp/kcov
    - run:
        name: Build
        command: |
          cd classify-client
          cargo build --release
    - run:
        name: Test
        command: |
          cd classify-client
          cargo test --release
    - run:
        name: Coverage
        command: |
          cd classify-client
          cargo kcov

workflows:
  test:
    jobs:
      - test-machine
