version: 2

jobs:
  build:
    docker:
      - image: debian:stretch
      - image: rust:1.31-stretch
    steps:
      - checkout
      - run:
          name: Check
          command: cargo check --all-targets --all-features
      - run:
          name: Rustfmt
          command: cargo fmt -- --check
      - run:
          name: Clippy
          command: cargo clippy --all-targets --all-features
      - run:
          name: Build
          command: cargo build --release
      - run:
          name: Test
          command: cargo test --release